# Generated by Django 3.2.7 on 2021-09-14 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_alter_district_specific_place_raging'),
    ]

    operations = [
        migrations.AlterField(
            model_name='district_specific_place',
            name='raging',
            field=models.IntegerField(choices=[('1', '*'), ('2', '**'), ('3', '***'), ('4', '****'), ('5', '*****')]),
        ),
    ]
