# Generated by Django 3.2.7 on 2021-09-14 11:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_alter_district_specific_place_raging'),
    ]

    operations = [
        migrations.RenameField(
            model_name='district_specific_place',
            old_name='raging',
            new_name='ratings',
        ),
    ]
