# Generated by Django 3.2.7 on 2021-09-15 12:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_rename_raging_district_specific_place_ratings'),
    ]

    operations = [
        migrations.CreateModel(
            name='District_details_video',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('video', models.FileField(upload_to='video')),
                ('description_video', models.TextField(max_length=200)),
                ('name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.district_specific_place')),
            ],
        ),
        migrations.CreateModel(
            name='District_details_gallary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_gallary', models.ImageField(upload_to='images')),
                ('description', models.TextField(max_length=200)),
                ('name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.district_specific_place')),
            ],
        ),
    ]
