# Generated by Django 3.2.7 on 2021-09-18 14:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_auto_20210918_1617'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='district_specific_place',
            name='user',
        ),
    ]
