# Generated by Django 3.2.7 on 2021-09-20 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0011_anonymouscontact_usercontact'),
    ]

    operations = [
        migrations.AddField(
            model_name='userinfo',
            name='Email',
            field=models.EmailField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='profile_pic',
            field=models.ImageField(blank=True, default='default.jpg', upload_to='profile_pics'),
        ),
    ]
