# Generated by Django 3.2.7 on 2021-09-24 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0013_booking_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking_user',
            name='created_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
