# Generated by Django 3.2.7 on 2021-09-24 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0014_booking_user_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking_user',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
