# Generated by Django 3.2.7 on 2021-09-24 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0017_booking_user_updated_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking_user',
            name='status',
            field=models.CharField(choices=[('in_progress', 'In Progress'), ('cancelled', 'Cancelled'), ('rejected', 'Rejected'), ('confirmed', 'Confirmed'), ('complete', 'Trip Complete')], default='in_progress', max_length=255),
        ),
    ]
