# Generated by Django 3.2.7 on 2021-09-28 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0018_booking_user_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='Packages',
            fields=[
                ('package_name', models.CharField(max_length=30, primary_key=True, serialize=False)),
                ('image', models.ImageField(upload_to='images')),
            ],
        ),
    ]
