# Generated by Django 3.2.7 on 2021-09-28 15:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0019_packages'),
    ]

    operations = [
        migrations.CreateModel(
            name='PackageDetail_S',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('place_name', models.CharField(max_length=80)),
                ('image', models.ImageField(upload_to='images')),
                ('description', models.TextField(max_length=200)),
                ('member', models.IntegerField()),
                ('duration', models.CharField(max_length=250)),
                ('price', models.IntegerField()),
                ('package_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.packages')),
            ],
        ),
    ]
