# Generated by Django 3.2.7 on 2021-09-28 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0020_packagedetail_s'),
    ]

    operations = [
        migrations.CreateModel(
            name='Footer_items',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('facebook', models.CharField(max_length=100)),
                ('Instagram', models.CharField(max_length=100)),
                ('Twitter', models.CharField(max_length=100)),
                ('Linkedin', models.CharField(max_length=150)),
            ],
        ),
    ]
