# Generated by Django 3.2.7 on 2021-09-29 17:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0021_footer_items'),
    ]

    operations = [
        migrations.CreateModel(
            name='PackageDetail_Place',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='images')),
                ('package_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.packagedetail_s')),
            ],
        ),
    ]
