# Generated by Django 3.2.7 on 2021-09-29 19:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0022_packagedetail_place'),
    ]

    operations = [
        migrations.CreateModel(
            name='Booking_Package',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('package_name', models.CharField(max_length=100)),
                ('place_name', models.CharField(max_length=50)),
                ('description', models.CharField(max_length=300)),
                ('mamber', models.IntegerField()),
                ('price', models.IntegerField()),
            ],
        ),
    ]
