# Generated by Django 3.2.7 on 2021-10-01 19:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0023_booking_package'),
    ]

    operations = [
        migrations.AddField(
            model_name='packagedetail_place',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='Package_Gallery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image1', models.ImageField(blank=True, null=True, upload_to='package_gallery')),
                ('image2', models.ImageField(blank=True, null=True, upload_to='package_gallery')),
                ('image3', models.ImageField(blank=True, null=True, upload_to='package_gallery')),
                ('image4', models.ImageField(blank=True, null=True, upload_to='package_gallery')),
                ('image5', models.ImageField(blank=True, null=True, upload_to='package_gallery')),
                ('image6', models.ImageField(blank=True, null=True, upload_to='package_gallery')),
                ('package_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.packagedetail_s')),
            ],
        ),
    ]
