# Generated by Django 3.2.7 on 2021-10-03 07:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('home', '0026_rename_package_item_package_gallery_package_items'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking_package',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='auth.user'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='booking_package',
            name='package_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.packages'),
        ),
        migrations.AlterField(
            model_name='booking_package',
            name='place_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.packagedetail_s'),
        ),
    ]
