# Generated by Django 3.2.7 on 2021-10-03 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0027_auto_20211003_1340'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking_package',
            name='description',
            field=models.TextField(),
        ),
    ]
