# Generated by Django 3.2.7 on 2021-10-04 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0028_alter_booking_package_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='district_details_gallary',
            name='image_gallary',
        ),
        migrations.AddField(
            model_name='district_details_gallary',
            name='image1',
            field=models.ImageField(blank=True, null=True, upload_to='gallery'),
        ),
        migrations.AddField(
            model_name='district_details_gallary',
            name='image2',
            field=models.ImageField(blank=True, null=True, upload_to='gallery'),
        ),
        migrations.AddField(
            model_name='district_details_gallary',
            name='image3',
            field=models.ImageField(blank=True, null=True, upload_to='gallery'),
        ),
        migrations.AddField(
            model_name='district_details_gallary',
            name='image4',
            field=models.ImageField(blank=True, null=True, upload_to='gallery'),
        ),
        migrations.AddField(
            model_name='district_details_gallary',
            name='image5',
            field=models.ImageField(blank=True, null=True, upload_to='gallery'),
        ),
        migrations.AddField(
            model_name='district_details_gallary',
            name='image6',
            field=models.ImageField(blank=True, null=True, upload_to='gallery'),
        ),
    ]
