# Generated by Django 3.2.7 on 2021-10-04 15:35

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0029_auto_20211004_1603'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking_package',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='booking_package',
            name='status',
            field=models.CharField(choices=[('in_progress', 'In Progress'), ('cancelled', 'Cancelled'), ('rejected', 'Rejected'), ('confirmed', 'Confirmed'), ('complete', 'Trip Complete')], default='in_progress', max_length=255),
        ),
        migrations.AddField(
            model_name='booking_package',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
